resources:
  repositories:
      - repository: MarkupProcessor
        type: git
        name: MarkupProcessor
        trigger:
          branches:
            include:
              - master

pool:
  vmImage: ubuntu-latest

stages:
    - stage: BuildTestPublishArtifact
      displayName: Build - Test - Publish
      jobs:
      - job: Build
        steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: '**/**/*.csproj'
            feedsToUse: 'select'
            vstsFeed: '804b14a9-0071-4078-9bae-9c71553dcc86'
            arguments: 
        
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '**/**/*.csproj'
            arguments: '--configuration $(BuildConfiguration) --no-restore'
        
        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '**/**/*(Tt)ests/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'
        
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
              command: publish
              projects: '**/**/*MarkupProcessor.csproj'
              arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish artifacts'
          inputs:
            PathtoPublish: $(build.artifactstagingdirectory)
            ArtifactName: PublishBuildArtifacts

        - task: TerraformInstaller@0
          displayName: 'install terraform'
          inputs:
            terraformVersion: 'latest'

    - stage: Deploy
      displayName: Deploy
      # condition: or(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')), eq(variables['ForceDeploy'], true))
      jobs:
      - job: DeployWebApp
        steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download Artifact
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'PublishBuildArtifacts'
            itemPattern: '**/*.zip'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: TerraformTaskV2@2
          displayName: 'Terraform Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Deploy/Terraform'
            backendServiceArm: 'Azure subscription 1(2b4c180f-f586-49ae-b769-67e1f059dcf6)'
            backendAzureRmResourceGroupName: 'TerraformStateEUW'
            backendAzureRmStorageAccountName: 'markupterraformstate'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'tf/$(Build.Repository.Name).tfstate'
        - task: TerraformTaskV2@2
          displayName: 'validate'
          inputs:
            provider: 'azurerm'
            command: 'validate'
        - task: TerraformTaskV2@2
          displayName: 'plan'
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Deploy/Terraform'
            environmentServiceNameAzureRM: 'Azure subscription 1(2b4c180f-f586-49ae-b769-67e1f059dcf6)'
        - task: TerraformTaskV2@2
          displayName: 'apply'
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Deploy/Terraform'
            environmentServiceNameAzureRM: 'Azure subscription 1(2b4c180f-f586-49ae-b769-67e1f059dcf6)'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure subscription 1(2b4c180f-f586-49ae-b769-67e1f059dcf6)'
            appType: 'webAppLinux'
            WebAppName: 'markup-processor-app'
            packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

        